# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import calculadora_pb2 as calculadora__pb2


class CalculadoraStub(object):
    def __init__(self, channel):
        self.Somar = channel.unary_unary(
                '/calculadora.Calculadora/Somar',
                request_serializer=calculadora__pb2.DoisNumeros.SerializeToString,
                response_deserializer=calculadora__pb2.Resultado.FromString,
                )
        self.Subtrair = channel.unary_unary(
                '/calculadora.Calculadora/Subtrair',
                request_serializer=calculadora__pb2.DoisNumeros.SerializeToString,
                response_deserializer=calculadora__pb2.Resultado.FromString,
                )
        self.Multiplicar = channel.unary_unary(
                '/calculadora.Calculadora/Multiplicar',
                request_serializer=calculadora__pb2.DoisNumeros.SerializeToString,
                response_deserializer=calculadora__pb2.Resultado.FromString,
                )
        self.Dividir = channel.unary_unary(
                '/calculadora.Calculadora/Dividir',
                request_serializer=calculadora__pb2.DoisNumeros.SerializeToString,
                response_deserializer=calculadora__pb2.Resultado.FromString,
                )
        self.CalcularPotencia = channel.unary_unary(
                '/calculadora.Calculadora/CalcularPotencia',
                request_serializer=calculadora__pb2.DoisNumeros.SerializeToString,
                response_deserializer=calculadora__pb2.Resultado.FromString,
                )
        self.CalcularRaizQuadrada = channel.unary_unary(
                '/calculadora.Calculadora/CalcularRaizQuadrada',
                request_serializer=calculadora__pb2.NumeroUnico.SerializeToString,
                response_deserializer=calculadora__pb2.Resultado.FromString,
                )
        self.SomarStream = channel.stream_unary(
                '/calculadora.Calculadora/SomarStream',
                request_serializer=calculadora__pb2.NumeroStream.SerializeToString,
                response_deserializer=calculadora__pb2.SomaTotal.FromString,
                )
        self.GerarTabuada = channel.unary_stream(
                '/calculadora.Calculadora/GerarTabuada',
                request_serializer=calculadora__pb2.EntradaTabuada.SerializeToString,
                response_deserializer=calculadora__pb2.LinhaTabuada.FromString,
                )
        self.CalcularMediaMovel = channel.stream_stream(
                '/calculadora.Calculadora/CalcularMediaMovel',
                request_serializer=calculadora__pb2.NumeroStream.SerializeToString,
                response_deserializer=calculadora__pb2.MediaParcial.FromString,
                )


class CalculadoraServicer(object):
    def Somar(self, request, context):
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subtrair(self, request, context):
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Multiplicar(self, request, context):
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Dividir(self, request, context):
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CalcularPotencia(self, request, context):
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CalcularRaizQuadrada(self, request, context):
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SomarStream(self, request_iterator, context):
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GerarTabuada(self, request, context):
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CalcularMediaMovel(self, request_iterator, context):
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


class _CalculadoraHandler(grpc.GenericRpcHandler):
    """
    GenericRpcHandler compatível com grpcio 1.80.
    Substitui grpc.method_service_handler que não existe nessa versão.
    """
    def __init__(self, servicer):
        self._handlers = {
            '/calculadora.Calculadora/Somar': grpc.unary_unary_rpc_method_handler(
                servicer.Somar,
                request_deserializer=calculadora__pb2.DoisNumeros.FromString,
                response_serializer=calculadora__pb2.Resultado.SerializeToString,
            ),
            '/calculadora.Calculadora/Subtrair': grpc.unary_unary_rpc_method_handler(
                servicer.Subtrair,
                request_deserializer=calculadora__pb2.DoisNumeros.FromString,
                response_serializer=calculadora__pb2.Resultado.SerializeToString,
            ),
            '/calculadora.Calculadora/Multiplicar': grpc.unary_unary_rpc_method_handler(
                servicer.Multiplicar,
                request_deserializer=calculadora__pb2.DoisNumeros.FromString,
                response_serializer=calculadora__pb2.Resultado.SerializeToString,
            ),
            '/calculadora.Calculadora/Dividir': grpc.unary_unary_rpc_method_handler(
                servicer.Dividir,
                request_deserializer=calculadora__pb2.DoisNumeros.FromString,
                response_serializer=calculadora__pb2.Resultado.SerializeToString,
            ),
            '/calculadora.Calculadora/CalcularPotencia': grpc.unary_unary_rpc_method_handler(
                servicer.CalcularPotencia,
                request_deserializer=calculadora__pb2.DoisNumeros.FromString,
                response_serializer=calculadora__pb2.Resultado.SerializeToString,
            ),
            '/calculadora.Calculadora/CalcularRaizQuadrada': grpc.unary_unary_rpc_method_handler(
                servicer.CalcularRaizQuadrada,
                request_deserializer=calculadora__pb2.NumeroUnico.FromString,
                response_serializer=calculadora__pb2.Resultado.SerializeToString,
            ),
            '/calculadora.Calculadora/SomarStream': grpc.stream_unary_rpc_method_handler(
                servicer.SomarStream,
                request_deserializer=calculadora__pb2.NumeroStream.FromString,
                response_serializer=calculadora__pb2.SomaTotal.SerializeToString,
            ),
            '/calculadora.Calculadora/GerarTabuada': grpc.unary_stream_rpc_method_handler(
                servicer.GerarTabuada,
                request_deserializer=calculadora__pb2.EntradaTabuada.FromString,
                response_serializer=calculadora__pb2.LinhaTabuada.SerializeToString,
            ),
            '/calculadora.Calculadora/CalcularMediaMovel': grpc.stream_stream_rpc_method_handler(
                servicer.CalcularMediaMovel,
                request_deserializer=calculadora__pb2.NumeroStream.FromString,
                response_serializer=calculadora__pb2.MediaParcial.SerializeToString,
            ),
        }

    def service(self, handler_call_details):
        return self._handlers.get(handler_call_details.method)


def add_CalculadoraServicer_to_server(servicer, server):
    server.add_generic_rpc_handlers((_CalculadoraHandler(servicer),))