# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: calculadora.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'calculadora.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63\x61lculadora.proto\x12\x0b\x63\x61lculadora\"#\n\x0b\x44oisNumeros\x12\t\n\x01\x61\x18\x01 \x01(\x01\x12\t\n\x01\x62\x18\x02 \x01(\x01\"\x1a\n\tResultado\x12\r\n\x05valor\x18\x01 \x01(\x01\"\x1d\n\x0bNumeroUnico\x12\x0e\n\x06numero\x18\x01 \x01(\x01\"\x1e\n\x0cNumeroStream\x12\x0e\n\x06numero\x18\x01 \x01(\x01\"\x1a\n\tSomaTotal\x12\r\n\x05total\x18\x01 \x01(\x01\" \n\x0e\x45ntradaTabuada\x12\x0e\n\x06numero\x18\x01 \x01(\x05\"8\n\x0cLinhaTabuada\x12\x15\n\rmultiplicador\x18\x01 \x01(\x05\x12\x11\n\tresultado\x18\x02 \x01(\x01\"/\n\x0cMediaParcial\x12\r\n\x05media\x18\x01 \x01(\x01\x12\x10\n\x08\x63ontagem\x18\x02 \x01(\x05\x32\xf2\x04\n\x0b\x43\x61lculadora\x12\x39\n\x05Somar\x12\x18.calculadora.DoisNumeros\x1a\x16.calculadora.Resultado\x12<\n\x08Subtrair\x12\x18.calculadora.DoisNumeros\x1a\x16.calculadora.Resultado\x12?\n\x0bMultiplicar\x12\x18.calculadora.DoisNumeros\x1a\x16.calculadora.Resultado\x12;\n\x07\x44ividir\x12\x18.calculadora.DoisNumeros\x1a\x16.calculadora.Resultado\x12\x44\n\x10\x43\x61lcularPotencia\x12\x18.calculadora.DoisNumeros\x1a\x16.calculadora.Resultado\x12H\n\x14\x43\x61lcularRaizQuadrada\x12\x18.calculadora.NumeroUnico\x1a\x16.calculadora.Resultado\x12\x42\n\x0bSomarStream\x12\x19.calculadora.NumeroStream\x1a\x16.calculadora.SomaTotal(\x01\x12H\n\x0cGerarTabuada\x12\x1b.calculadora.EntradaTabuada\x1a\x19.calculadora.LinhaTabuada0\x01\x12N\n\x12\x43\x61lcularMediaMovel\x12\x19.calculadora.NumeroStream\x1a\x19.calculadora.MediaParcial(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calculadora_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DOISNUMEROS']._serialized_start=34
  _globals['_DOISNUMEROS']._serialized_end=69
  _globals['_RESULTADO']._serialized_start=71
  _globals['_RESULTADO']._serialized_end=97
  _globals['_NUMEROUNICO']._serialized_start=99
  _globals['_NUMEROUNICO']._serialized_end=128
  _globals['_NUMEROSTREAM']._serialized_start=130
  _globals['_NUMEROSTREAM']._serialized_end=160
  _globals['_SOMATOTAL']._serialized_start=162
  _globals['_SOMATOTAL']._serialized_end=188
  _globals['_ENTRADATABUADA']._serialized_start=190
  _globals['_ENTRADATABUADA']._serialized_end=222
  _globals['_LINHATABUADA']._serialized_start=224
  _globals['_LINHATABUADA']._serialized_end=280
  _globals['_MEDIAPARCIAL']._serialized_start=282
  _globals['_MEDIAPARCIAL']._serialized_end=329
  _globals['_CALCULADORA']._serialized_start=332
  _globals['_CALCULADORA']._serialized_end=958
# @@protoc_insertion_point(module_scope)
