# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import calculadora_pb2 as calculadora__pb2


class CalculadoraStub(object):
    """── Serviço ───────────────────────────────────────────────────────────────────"""

    def __init__(self, channel):
        self.Somar = channel.unary_unary(
                '/calculadora.Calculadora/Somar',
                request_serializer=calculadora__pb2.DoisNumeros.SerializeToString,
                response_deserializer=calculadora__pb2.Resultado.FromString,
                )
        self.Subtrair = channel.unary_unary(
                '/calculadora.Calculadora/Subtrair',
                request_serializer=calculadora__pb2.DoisNumeros.SerializeToString,
                response_deserializer=calculadora__pb2.Resultado.FromString,
                )
        self.Multiplicar = channel.unary_unary(
                '/calculadora.Calculadora/Multiplicar',
                request_serializer=calculadora__pb2.DoisNumeros.SerializeToString,
                response_deserializer=calculadora__pb2.Resultado.FromString,
                )
        self.Dividir = channel.unary_unary(
                '/calculadora.Calculadora/Dividir',
                request_serializer=calculadora__pb2.DoisNumeros.SerializeToString,
                response_deserializer=calculadora__pb2.Resultado.FromString,
                )
        self.CalcularPotencia = channel.unary_unary(
                '/calculadora.Calculadora/CalcularPotencia',
                request_serializer=calculadora__pb2.DoisNumeros.SerializeToString,
                response_deserializer=calculadora__pb2.Resultado.FromString,
                )
        self.CalcularRaizQuadrada = channel.unary_unary(
                '/calculadora.Calculadora/CalcularRaizQuadrada',
                request_serializer=calculadora__pb2.NumeroUnico.SerializeToString,
                response_deserializer=calculadora__pb2.Resultado.FromString,
                )
        self.SomarStream = channel.stream_unary(
                '/calculadora.Calculadora/SomarStream',
                request_serializer=calculadora__pb2.NumeroStream.SerializeToString,
                response_deserializer=calculadora__pb2.SomaTotal.FromString,
                )
        self.GerarTabuada = channel.unary_stream(
                '/calculadora.Calculadora/GerarTabuada',
                request_serializer=calculadora__pb2.EntradaTabuada.SerializeToString,
                response_deserializer=calculadora__pb2.LinhaTabuada.FromString,
                )
        self.CalcularMediaMovel = channel.stream_stream(
                '/calculadora.Calculadora/CalcularMediaMovel',
                request_serializer=calculadora__pb2.NumeroStream.SerializeToString,
                response_deserializer=calculadora__pb2.MediaParcial.FromString,
                )


class CalculadoraServicer(object):
    """── Serviço ───────────────────────────────────────────────────────────────────"""

    def Somar(self, request, context):
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subtrair(self, request, context):
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Multiplicar(self, request, context):
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Dividir(self, request, context):
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CalcularPotencia(self, request, context):
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CalcularRaizQuadrada(self, request, context):
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SomarStream(self, request_iterator, context):
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GerarTabuada(self, request, context):
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CalcularMediaMovel(self, request_iterator, context):
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CalculadoraServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Somar': grpc.unary_unary_rpc_method_handler(
                    servicer.Somar,
                    request_deserializer=calculadora__pb2.DoisNumeros.FromString,
                    response_serializer=calculadora__pb2.Resultado.SerializeToString,
            ),
            'Subtrair': grpc.unary_unary_rpc_method_handler(
                    servicer.Subtrair,
                    request_deserializer=calculadora__pb2.DoisNumeros.FromString,
                    response_serializer=calculadora__pb2.Resultado.SerializeToString,
            ),
            'Multiplicar': grpc.unary_unary_rpc_method_handler(
                    servicer.Multiplicar,
                    request_deserializer=calculadora__pb2.DoisNumeros.FromString,
                    response_serializer=calculadora__pb2.Resultado.SerializeToString,
            ),
            'Dividir': grpc.unary_unary_rpc_method_handler(
                    servicer.Dividir,
                    request_deserializer=calculadora__pb2.DoisNumeros.FromString,
                    response_serializer=calculadora__pb2.Resultado.SerializeToString,
            ),
            'CalcularPotencia': grpc.unary_unary_rpc_method_handler(
                    servicer.CalcularPotencia,
                    request_deserializer=calculadora__pb2.DoisNumeros.FromString,
                    response_serializer=calculadora__pb2.Resultado.SerializeToString,
            ),
            'CalcularRaizQuadrada': grpc.unary_unary_rpc_method_handler(
                    servicer.CalcularRaizQuadrada,
                    request_deserializer=calculadora__pb2.NumeroUnico.FromString,
                    response_serializer=calculadora__pb2.Resultado.SerializeToString,
            ),
            'SomarStream': grpc.stream_unary_rpc_method_handler(
                    servicer.SomarStream,
                    request_deserializer=calculadora__pb2.NumeroStream.FromString,
                    response_serializer=calculadora__pb2.SomaTotal.SerializeToString,
            ),
            'GerarTabuada': grpc.unary_stream_rpc_method_handler(
                    servicer.GerarTabuada,
                    request_deserializer=calculadora__pb2.EntradaTabuada.FromString,
                    response_serializer=calculadora__pb2.LinhaTabuada.SerializeToString,
            ),
            'CalcularMediaMovel': grpc.stream_stream_rpc_method_handler(
                    servicer.CalcularMediaMovel,
                    request_deserializer=calculadora__pb2.NumeroStream.FromString,
                    response_serializer=calculadora__pb2.MediaParcial.SerializeToString,
            ),
    }
    generic_handler = grpc.method_service_handler(
            'calculadora.Calculadora', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
